export enum EstadoSolicitud {
  PENDIENTE = 'PENDIENTE',
  EN_REVISION = 'EN_REVISION',
  PRESELECCIONADA = 'PRESELECCIONADA',
  ACEPTADA = 'ACEPTADA',
  RECHAZADA = 'RECHAZADA',
  OFERTA_ELIMINADA = 'OFERTA_ELIMINADA',
  CANCELADA = 'CANCELADA',
}